apiVersion: v2
name: my-app
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: frontend
    version: 0.0.1
    repository: "file://charts/frontend"
  - name: backend
    version: 0.0.1
    repository: "file://charts/backend"
  - name: database
    version: 0.0.1
    repository: "file://charts/database"