# Default values for my-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

frontend:
  replicas: 2
  service:
    type: ClusterIP
    port: 80
  image:
    repository: frontend-image
    pullPolicy: IfNotPresent
    tag: latest
backend:
  replicas: 3
  service:
    type: ClusterIP
    port: 8080
  image:
    repository: backend-image
    pullPolicy: IfNotPresent
    tag: latest
database:
  name: database
  replicas: 1
  service:
    type: ClusterIP
    port: 3306
  image:
    repository: mysql
    pullPolicy: IfNotPresent
    tag: latest
  pvc:
    accessMode: ReadWriteOnce
    storage: 2Gi