apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: database
spec:
  replicas: {{ .Values.database.replicas }}
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: {{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}
        ports:
        - containerPort: {{ .Values.database.service.port }}