apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.name }}-claim
spec:
  storageClassName: manual
  accessModes:
    - {{ .Values.database.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.database.pvc.storage }}
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: task-pv-claim